# Generated by Django 3.2.23 on 2024-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='/static/assets/profile.svg', upload_to='Gallery/profile_pic'),
        ),
    ]
