# Generated by Django 3.2.23 on 2024-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='viewerform',
        ),
    ]
