# Generated by Django 3.2.23 on 2024-01-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0003_rename_email_viewerregister_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pagename', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewerregister',
            name='date',
        ),
    ]
