# Generated by Django 3.2.23 on 2024-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0004_auto_20240122_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='pagename',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='userregister',
            name='page_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(default='default_value', max_length=15),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='gmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
