# Generated by Django 3.2.23 on 2024-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0005_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
