# Generated by Django 3.2.23 on 2024-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0005_auto_20240122_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerregister',
            name='gmail',
            field=models.EmailField(max_length=254),
        ),
    ]
