# Generated by Django 3.2.23 on 2024-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0006_alter_viewerregister_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('post', models.FileField(default=None, max_length=250, null=True, upload_to='media/')),
            ],
        ),
    ]
