# Generated by Django 3.2.23 on 2024-02-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0006_alter_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
