# Generated by Django 3.2.23 on 2024-01-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0007_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
