# Generated by Django 3.2.23 on 2024-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0008_rename_posts_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='posts/'),
        ),
    ]
