# Generated by Django 3.2.23 on 2024-01-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0009_auto_20240125_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
