# Generated by Django 3.2.23 on 2024-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'main_user'), (2, 'viewer'), (3, 'profile')], max_length=50),
        ),
    ]
