# Generated by Django 3.2.23 on 2024-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0011_userregister_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='page_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='profile_pic',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile_pic/'),
        ),
    ]
