# Generated by Django 3.2.23 on 2024-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0011_auto_20240215_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='Gallery/profilepic/profile.svg', upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'profile'), (2, 'viewer')], default=2, max_length=50),
        ),
    ]
