# Generated by Django 3.2.23 on 2024-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0014_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[(2, 'viewer'), (1, 'profile')], max_length=10),
        ),
    ]
