# Generated by Django 3.2.23 on 2024-01-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0014_userregister_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='profile_pic',
        ),
    ]
