# Generated by Django 3.2.23 on 2024-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0018_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profilepic/profile.svg', upload_to='profilepic'),
        ),
    ]
