# Generated by Django 3.2.23 on 2024-02-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0019_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='static/svg/profile.svg', upload_to='profilepic'),
        ),
    ]
