# Generated by Django 3.2.23 on 2024-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0019_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='desc',
        ),
    ]
