# Generated by Django 3.2.23 on 2024-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0020_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'viewer'), (2, 'profile')], default=1, max_length=15),
        ),
    ]
