# Generated by Django 3.2.23 on 2024-01-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0021_userregister_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
