# Generated by Django 3.2.23 on 2024-02-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0022_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.TextField(choices=[(1, 'viewer'), (2, 'profile')], default=1, max_length=255, null=True),
        ),
    ]
