# Generated by Django 3.2.23 on 2024-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0026_auto_20240131_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userregister',
            name='profile_pic',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile_pic/'),
        ),
    ]
