# Generated by Django 3.2.23 on 2024-01-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0027_auto_20240131_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='profile_pic',
        ),
    ]
