# Generated by Django 3.2.23 on 2024-02-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0028_profile_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='updated_at',
        ),
    ]
