# Generated by Django 3.2.23 on 2024-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0029_auto_20240215_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('viewer', 'VIEWER'), ('profile', 'PROFILE')], default='viewer', max_length=255),
        ),
    ]
