# Generated by Django 3.2.23 on 2024-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0029_userregister_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bio',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='profile_pic',
            field=models.FileField(default='Gallery/posts/adi_YwHjEXJ.jpg', max_length=250, null=True, upload_to='profile_pic/'),
        ),
    ]
