# Generated by Django 3.2.23 on 2024-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0032_alter_userregister_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profile_pic',
            field=models.FileField(default='Gallery\\profile_pic\\_b231865a-912a-4fb6-970f-028b2396ddf5.jpeg', max_length=250, null=True, upload_to='profile_pic/'),
        ),
    ]
