# Generated by Django 3.2.23 on 2024-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0035_auto_20240216_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=1),
        ),
    ]
