# Generated by Django 3.2.23 on 2024-02-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0037_alter_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
