# Generated by Django 3.2.23 on 2024-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0038_remove_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
