# Generated by Django 3.2.23 on 2024-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0041_alter_userregister_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='bio',
            field=models.CharField(default='add bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='page_name',
            field=models.CharField(default='Enter page name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
