# Generated by Django 3.2.23 on 2024-03-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0042_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
