# Generated by Django 3.2.23 on 2024-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0042_auto_20240131_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='bio',
            field=models.CharField(default='add bio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='page_name',
            field=models.CharField(default='Enter page name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
