# Generated by Django 3.2.23 on 2024-01-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0044_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewerregister',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
