# Generated by Django 3.2.23 on 2024-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0045_viewerregister_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='post',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='posts/'),
        ),
    ]
