# Generated by Django 3.2.23 on 2024-03-05 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0059_auto_20240305_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f87a3d0-340d-4ffe-a4ff-866f671217bb'), primary_key=True, serialize=False),
        ),
    ]
