# Generated by Django 3.2.23 on 2024-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0060_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='a3ad48a11a3a4963af9dc17a777dd09d', primary_key=True, serialize=False),
        ),
    ]
