# Generated by Django 3.2.23 on 2024-03-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0061_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
