# Generated by Django 3.2.23 on 2024-03-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0067_auto_20240305_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='uid',
        ),
    ]
