# Generated by Django 3.2.23 on 2024-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0068_rename_id_post_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='id',
        ),
    ]
