# Generated by Django 3.2.23 on 2024-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0073_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='profile',
        ),
    ]
