# Generated by Django 3.2.23 on 2024-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0075_auto_20240305_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_id',
            field=models.IntegerField(null=True),
        ),
    ]
