# Generated by Django 3.2.23 on 2024-03-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0076_profile_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='u_id',
        ),
    ]
