# Generated by Django 3.2.23 on 2024-03-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0077_remove_profile_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile',
        ),
    ]
