# Generated by Django 3.2.23 on 2024-03-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0078_rename_user_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
