# Generated by Django 3.2.23 on 2024-03-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0079_rename_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default='static/assets/svg/profile.svg', upload_to='profilepic'),
        ),
    ]
