# Generated by Django 3.2.23 on 2024-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0081_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='profilepic'),
        ),
    ]
