# Generated by Django 3.2.23 on 2024-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0082_auto_20240306_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profilepic'),
        ),
    ]
