# Generated by Django 3.2.23 on 2024-03-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0105_followerscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='user',
        ),
    ]
