# Generated by Django 3.2.23 on 2024-03-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0106_remove_followerscount_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
