# Generated by Django 3.2.23 on 2024-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0109_alter_followerscount_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(max_length=100),
        ),
    ]
