# Generated by Django 3.2.23 on 2024-03-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0110_alter_followerscount_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='follower',
        ),
    ]
