# Generated by Django 3.2.23 on 2024-03-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0113_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
