# Generated by Django 3.2.23 on 2024-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0119_post_no_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_comments',
        ),
    ]
