# Generated by Django 3.2.23 on 2024-03-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0120_remove_post_no_of_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='username',
            new_name='user',
        ),
    ]
