# Generated by Django 3.2.23 on 2024-03-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0121_rename_username_commentpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='user',
            new_name='username',
        ),
    ]
