# Generated by Django 3.2.23 on 2024-03-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0122_rename_user_commentpost_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='username',
            new_name='user',
        ),
    ]
