# Generated by Django 3.2.23 on 2024-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0123_rename_username_commentpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
