# Generated by Django 3.2.23 on 2024-03-13 13:10

from django.db import migrations, models
import socialweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0125_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='', verbose_name=socialweb.models.CustomUser),
        ),
    ]
