# Generated by Django 3.2.23 on 2024-03-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0126_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profilepic',
        ),
    ]
