# Generated by Django 3.2.23 on 2024-03-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0127_rename_profile_pic_profile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilepic',
        ),
    ]
