# Generated by Django 3.2.23 on 2024-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0132_auto_20240313_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
