# Generated by Django 3.2.23 on 2024-03-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0133_auto_20240313_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
