# Generated by Django 3.2.23 on 2024-03-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0135_auto_20240314_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialweb.profile')),
            ],
        ),
    ]
