# Generated by Django 3.2.23 on 2024-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0136_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='gmail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
