# Generated by Django 3.2.23 on 2024-03-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0140_auto_20240316_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='profile',
        ),
    ]
