# Generated by Django 3.2.23 on 2024-03-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0141_rename_user_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='user',
        ),
    ]
