# Generated by Django 3.2.23 on 2024-03-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0144_auto_20240316_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='user',
        ),
    ]
