# Generated by Django 3.2.23 on 2024-03-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0145_remove_links_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialweb.profile'),
        ),
    ]
