# Generated by Django 3.2.23 on 2024-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0148_auto_20240316_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default='/static/assets/svg/profile.svg', null=True, upload_to='profilepic'),
        ),
    ]
