# Generated by Django 3.2.23 on 2024-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0150_auto_20240316_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtube',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
