# Generated by Django 3.2.23 on 2024-03-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0151_auto_20240316_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube',
        ),
    ]
