# Generated by Django 3.2.23 on 2024-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0152_auto_20240316_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.FileField(null=True, upload_to='post/videos'),
        ),
    ]
