# Generated by Django 3.2.23 on 2024-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0153_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.FileField(null=True, upload_to='post'),
        ),
    ]
