# Generated by Django 3.2.23 on 2024-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0154_alter_post_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videos',
        ),
    ]
