# Generated by Django 3.2.23 on 2024-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0155_remove_post_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='post'),
        ),
    ]
