# Generated by Django 3.2.23 on 2024-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0157_auto_20240321_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
