# Generated by Django 3.2.23 on 2024-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('media', models.FileField(default=None, max_length=250, null=True, upload_to='posts/')),
            ],
        ),
    ]
